spring:
  profiles:
    active: dev
  application:
    name: user-service,common,pg,eureka
  cloud:
    config:
      uri: http://localhost:8082
      profile: dev
  config:
    import: configserver:http://localhost:8082