spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        jdbc:
          enabled: false
        native:
          search-locations: classpath:config/
        bootstrap: true
      profile: dev
      uri: http://localhost:8082/
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5