server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway